model_name: "ConvE"
datasets:
  - dataset: "fb15k_237"
    parameters:
      learning_rate: 0.1
      l1_flag': True
      hidden_size: 50
      hidden_size_1: 20
      input_dropout: 0.2
      feature_map_dropout: 0.2
      hidden_dropout: 0.3
      label_smoothing: 0.1
      batch_size: 50
      optimizer: "adam"
      neg_rate: 1
      sampling: "adversarial_negative_sampling"
      epochs: 100
  - dataset: "freebase15k"
    parameters:
      learning_rate: 0.1
      l1_flag': True
      hidden_size: 50
      hidden_size_1: 20
      input_dropout: 0.2
      feature_map_dropout: 0.2
      hidden_dropout: 0.3
      label_smoothing: 0.1
      batch_size: 50
      optimizer: "adam"
      neg_rate: 1
      sampling: "adversarial_negative_sampling"
      epochs: 100
  - dataset: "wn18_rr"
    parameters:
      learning_rate: 0.1
      l1_flag': True
      hidden_size: 50
      hidden_size_1: 20
      input_dropout: 0.2
      feature_map_dropout: 0.2
      hidden_dropout: 0.3
      label_smoothing: 0.1
      batch_size: 50
      optimizer: "adam"
      neg_rate: 1
      sampling: "adversarial_negative_sampling"
      epochs: 100
  - dataset: "wn18"
    parameters:
      learning_rate: 0.1
      l1_flag': True
      hidden_size: 50
      hidden_size_1: 20
      input_dropout: 0.2
      feature_map_dropout: 0.2
      hidden_dropout: 0.3
      label_smoothing: 0.1
      batch_size: 50
      optimizer: "adam"
      neg_rate: 1
      sampling: "adversarial_negative_sampling"
      epochs: 100
