model_name: "TransR"
datasets:
  - dataset: "fb15k_237"
    parameters:
      learning_rate: 0.1
      l1_flag: True
      ent_hidden_size: 50
      rel_hidden_size: 50
      batch_size: 50
      epochs: 100
      margin: 4.0
      optimizer: "adam"
      sampling: "adversarial_negative_sampling"
      neg_rate: 1
      lmbda: 0.0001
  - dataset: "freebase15k"
    parameters:
      learning_rate: 0.1
      l1_flag: True
      ent_hidden_size: 50
      rel_hidden_size: 50
      batch_size: 50
      epochs: 100
      margin: 1.0
      optimizer: "adam"
      sampling: "adversarial_negative_sampling"
      neg_rate: 1
      lmbda: 0.0001
  - dataset: "wn18_rr"
    parameters:
      learning_rate: 0.1
      l1_flag: True
      ent_hidden_size: 50
      rel_hidden_size: 50
      batch_size: 50
      epochs: 100
      margin: 4.0
      optimizer: "adam"
      sampling: "adversarial_negative_sampling"
      neg_rate: 1
      lmbda: 0.0001
  - dataset: "wn18"
    parameters:
      learning_rate: 0.1
      l1_flag: True
      ent_hidden_size: 50
      rel_hidden_size: 50
      batch_size: 50
      epochs: 100
      margin: 4.0
      optimizer: "adam"
      sampling: "adversarial_negative_sampling"
      neg_rate: 1
      lmbda: 0.0001
